export const doctors = [
  {
    id: 1,
    name: "Dr. Sarah Johnson",
    specialty: "Cardiology",
    experience: "15 years",
    rating: 4.9,
    patients: 2500,
    image: "/female-doctor-cardiologist.jpg",
    availability: ["Mon", "Wed", "Fri"],
    education: "MD, Harvard Medical School",
    about: "Specialized in interventional cardiology with focus on minimally invasive procedures.",
  },
  {
    id: 2,
    name: "Dr. Michael Chen",
    specialty: "Neurology",
    experience: "12 years",
    rating: 4.8,
    patients: 1800,
    image: "/male-doctor-neurologist.jpg",
    availability: ["Tue", "Thu", "Sat"],
    education: "MD, Johns Hopkins University",
    about: "Expert in treating neurological disorders and brain health optimization.",
  },
  {
    id: 3,
    name: "Dr. Emily Rodriguez",
    specialty: "Pediatrics",
    experience: "10 years",
    rating: 5.0,
    patients: 3200,
    image: "/female-doctor-pediatrician.jpg",
    availability: ["Mon", "Tue", "Wed", "Thu", "Fri"],
    education: "MD, Stanford University",
    about: "Passionate about child healthcare and developmental pediatrics.",
  },
  {
    id: 4,
    name: "Dr. James Wilson",
    specialty: "Orthopedics",
    experience: "18 years",
    rating: 4.7,
    patients: 2100,
    image: "/male-doctor-orthopedic-surgeon.jpg",
    availability: ["Mon", "Wed", "Fri"],
    education: "MD, Mayo Clinic",
    about: "Specializing in sports medicine and joint replacement surgery.",
  },
  {
    id: 5,
    name: "Dr. Priya Patel",
    specialty: "Dermatology",
    experience: "8 years",
    rating: 4.9,
    patients: 1500,
    image: "/female-doctor-dermatologist.jpg",
    availability: ["Tue", "Thu", "Sat"],
    education: "MD, Columbia University",
    about: "Expert in cosmetic and medical dermatology treatments.",
  },
  {
    id: 6,
    name: "Dr. Robert Taylor",
    specialty: "General Surgery",
    experience: "20 years",
    rating: 4.8,
    patients: 2800,
    image: "/male-doctor-surgeon.jpg",
    availability: ["Mon", "Tue", "Wed"],
    education: "MD, Yale School of Medicine",
    about: "Experienced in laparoscopic and robotic-assisted surgery.",
  },
]

export const appointments = [
  {
    id: 1,
    patientName: "John Smith",
    doctorName: "Dr. Sarah Johnson",
    specialty: "Cardiology",
    date: "2025-01-15",
    time: "10:00 AM",
    status: "confirmed",
    type: "Follow-up",
  },
  {
    id: 2,
    patientName: "Emma Davis",
    doctorName: "Dr. Emily Rodriguez",
    specialty: "Pediatrics",
    date: "2025-01-15",
    time: "11:30 AM",
    status: "confirmed",
    type: "Check-up",
  },
  {
    id: 3,
    patientName: "Michael Brown",
    doctorName: "Dr. James Wilson",
    specialty: "Orthopedics",
    date: "2025-01-16",
    time: "2:00 PM",
    status: "pending",
    type: "Consultation",
  },
  {
    id: 4,
    patientName: "Lisa Anderson",
    doctorName: "Dr. Priya Patel",
    specialty: "Dermatology",
    date: "2025-01-16",
    time: "3:30 PM",
    status: "confirmed",
    type: "Treatment",
  },
  {
    id: 5,
    patientName: "David Martinez",
    doctorName: "Dr. Michael Chen",
    specialty: "Neurology",
    date: "2025-01-17",
    time: "9:00 AM",
    status: "cancelled",
    type: "Consultation",
  },
]

export const patients = [
  {
    id: 1,
    name: "John Smith",
    age: 45,
    gender: "Male",
    bloodType: "O+",
    phone: "+1 (555) 123-4567",
    email: "john.smith@email.com",
    address: "123 Main St, New York, NY 10001",
    lastVisit: "2025-01-10",
    upcomingAppointments: 1,
  },
  {
    id: 2,
    name: "Emma Davis",
    age: 8,
    gender: "Female",
    bloodType: "A+",
    phone: "+1 (555) 234-5678",
    email: "emma.davis@email.com",
    address: "456 Oak Ave, Brooklyn, NY 11201",
    lastVisit: "2025-01-12",
    upcomingAppointments: 1,
  },
  {
    id: 3,
    name: "Michael Brown",
    age: 52,
    gender: "Male",
    bloodType: "B+",
    phone: "+1 (555) 345-6789",
    email: "michael.brown@email.com",
    address: "789 Pine Rd, Queens, NY 11354",
    lastVisit: "2025-01-08",
    upcomingAppointments: 1,
  },
]

export const stats = {
  totalPatients: 12500,
  totalDoctors: 85,
  totalAppointments: 3420,
  satisfactionRate: 98,
}
